package `in`.v89bhp.obdscanner.enums

enum class HandlerMessageCodes {
    MESSAGE_SNACKBAR, MESSAGE_ERROR, MESSAGE_RESPONSE, MESSAGE_RESPONSE_SCALING_FACTORS, MESSAGE_RESPONSE_INITIALIZATION,
    MESSAGE_RESPONSE_AT_COMMAND, MESSAGE_RESPONSE_VIN,

    MESSAGE_ERROR_IGNORABLE, MESSAGE_ERROR_BUS_BUSY, MESSAGE_ERROR_IGNITION_OFF
}